# docker-compose.yml
version: '3'
services:
 kreilinger:
    image: masterarbeitkreilinger:1.0
    user: $UID:$GID
    working_dir: $HOME
    stdin_open: true
    volumes:
      - /home/lkreilinger/Masterarbeit/output:/output
      - /home/lkreilinger/Masterarbeit/data:/data
    tty: true
    command: tail -f /dev/null